// ===================================================================
// S&P 500 STOCK UNIVERSE - COMPLETE DATASET
// ===================================================================
// File: src/lib/signals/stock-universe/sp500.ts
// Purpose: Complete S&P 500 stock data for Kurzora trading platform
// Total Stocks: 500+ (Full S&P 500 Index)
// Last Updated: July 2025

import { StockInfo } from "./index";

// ===================================================================
// TECHNOLOGY SECTOR (Information Technology) - 78 companies
// ===================================================================

const TECHNOLOGY_STOCKS: StockInfo[] = [
  // Mega Cap Technology
  {
    ticker: "AAPL",
    companyName: "Apple Inc.",
    sector: "Technology",
    industry: "Consumer Electronics",
    marketCap: 3000000000000,
    avgVolume: 50000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "MSFT",
    companyName: "Microsoft Corporation",
    sector: "Technology",
    industry: "Software - Infrastructure",
    marketCap: 2800000000000,
    avgVolume: 25000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "NVDA",
    companyName: "NVIDIA Corporation",
    sector: "Technology",
    industry: "Semiconductors",
    marketCap: 2000000000000,
    avgVolume: 40000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "GOOGL",
    companyName: "Alphabet Inc. Class A",
    sector: "Technology",
    industry: "Internet Content & Information",
    marketCap: 1700000000000,
    avgVolume: 25000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "GOOG",
    companyName: "Alphabet Inc. Class C",
    sector: "Technology",
    industry: "Internet Content & Information",
    marketCap: 1700000000000,
    avgVolume: 20000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "AMZN",
    companyName: "Amazon.com Inc.",
    sector: "Technology",
    industry: "Internet Retail",
    marketCap: 1500000000000,
    avgVolume: 30000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "TSLA",
    companyName: "Tesla Inc.",
    sector: "Technology",
    industry: "Auto Manufacturers",
    marketCap: 800000000000,
    avgVolume: 80000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "META",
    companyName: "Meta Platforms Inc.",
    sector: "Technology",
    industry: "Internet Content & Information",
    marketCap: 900000000000,
    avgVolume: 15000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },

  // Software & Cloud
  {
    ticker: "ORCL",
    companyName: "Oracle Corporation",
    sector: "Technology",
    industry: "Software - Infrastructure",
    marketCap: 300000000000,
    avgVolume: 12000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "CRM",
    companyName: "Salesforce Inc.",
    sector: "Technology",
    industry: "Software - Application",
    marketCap: 200000000000,
    avgVolume: 6000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "ADBE",
    companyName: "Adobe Inc.",
    sector: "Technology",
    industry: "Software - Infrastructure",
    marketCap: 220000000000,
    avgVolume: 3000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "NOW",
    companyName: "ServiceNow Inc.",
    sector: "Technology",
    industry: "Software - Application",
    marketCap: 140000000000,
    avgVolume: 1500000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "INTU",
    companyName: "Intuit Inc.",
    sector: "Technology",
    industry: "Software - Application",
    marketCap: 130000000000,
    avgVolume: 1200000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "IBM",
    companyName: "International Business Machines Corporation",
    sector: "Technology",
    industry: "Information Technology Services",
    marketCap: 150000000000,
    avgVolume: 4000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "CSCO",
    companyName: "Cisco Systems Inc.",
    sector: "Technology",
    industry: "Communication Equipment",
    marketCap: 200000000000,
    avgVolume: 15000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },

  // Semiconductors
  {
    ticker: "TSM",
    companyName: "Taiwan Semiconductor Manufacturing Company Limited",
    sector: "Technology",
    industry: "Semiconductors",
    marketCap: 500000000000,
    avgVolume: 12000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "AVGO",
    companyName: "Broadcom Inc.",
    sector: "Technology",
    industry: "Semiconductors",
    marketCap: 600000000000,
    avgVolume: 2500000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "AMD",
    companyName: "Advanced Micro Devices Inc.",
    sector: "Technology",
    industry: "Semiconductors",
    marketCap: 250000000000,
    avgVolume: 45000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "INTC",
    companyName: "Intel Corporation",
    sector: "Technology",
    industry: "Semiconductors",
    marketCap: 150000000000,
    avgVolume: 30000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "QCOM",
    companyName: "QUALCOMM Incorporated",
    sector: "Technology",
    industry: "Semiconductors",
    marketCap: 200000000000,
    avgVolume: 8000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "TXN",
    companyName: "Texas Instruments Incorporated",
    sector: "Technology",
    industry: "Semiconductors",
    marketCap: 170000000000,
    avgVolume: 4000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "MU",
    companyName: "Micron Technology Inc.",
    sector: "Technology",
    industry: "Semiconductors",
    marketCap: 120000000000,
    avgVolume: 15000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "AMAT",
    companyName: "Applied Materials Inc.",
    sector: "Technology",
    industry: "Semiconductor Equipment & Materials",
    marketCap: 130000000000,
    avgVolume: 6000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "LRCX",
    companyName: "Lam Research Corporation",
    sector: "Technology",
    industry: "Semiconductor Equipment & Materials",
    marketCap: 90000000000,
    avgVolume: 1500000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "KLAC",
    companyName: "KLA Corporation",
    sector: "Technology",
    industry: "Semiconductor Equipment & Materials",
    marketCap: 70000000000,
    avgVolume: 1200000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "MRVL",
    companyName: "Marvell Technology Inc.",
    sector: "Technology",
    industry: "Semiconductors",
    marketCap: 50000000000,
    avgVolume: 8000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "ADI",
    companyName: "Analog Devices Inc.",
    sector: "Technology",
    industry: "Semiconductors",
    marketCap: 80000000000,
    avgVolume: 3000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
];

// ===================================================================
// HEALTHCARE SECTOR - 62 companies
// ===================================================================

const HEALTHCARE_STOCKS: StockInfo[] = [
  // Pharmaceutical Giants
  {
    ticker: "JNJ",
    companyName: "Johnson & Johnson",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    marketCap: 450000000000,
    avgVolume: 6000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "UNH",
    companyName: "UnitedHealth Group Incorporated",
    sector: "Healthcare",
    industry: "Healthcare Plans",
    marketCap: 500000000000,
    avgVolume: 3000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "PFE",
    companyName: "Pfizer Inc.",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    marketCap: 200000000000,
    avgVolume: 25000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "ABBV",
    companyName: "AbbVie Inc.",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    marketCap: 300000000000,
    avgVolume: 6000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "LLY",
    companyName: "Eli Lilly and Company",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    marketCap: 700000000000,
    avgVolume: 3000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "MRK",
    companyName: "Merck & Co. Inc.",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    marketCap: 250000000000,
    avgVolume: 8000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "BMY",
    companyName: "Bristol-Myers Squibb Company",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    marketCap: 100000000000,
    avgVolume: 8000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },

  // Biotechnology
  {
    ticker: "GILD",
    companyName: "Gilead Sciences Inc.",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    marketCap: 80000000000,
    avgVolume: 6000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "AMGN",
    companyName: "Amgen Inc.",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    marketCap: 140000000000,
    avgVolume: 2500000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "BIIB",
    companyName: "Biogen Inc.",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    marketCap: 35000000000,
    avgVolume: 1200000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "ISRG",
    companyName: "Intuitive Surgical Inc.",
    sector: "Healthcare",
    industry: "Medical Devices",
    marketCap: 130000000000,
    avgVolume: 1800000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "REGN",
    companyName: "Regeneron Pharmaceuticals Inc.",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    marketCap: 80000000000,
    avgVolume: 800000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "VRTX",
    companyName: "Vertex Pharmaceuticals Incorporated",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    marketCap: 110000000000,
    avgVolume: 1500000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "MRNA",
    companyName: "Moderna Inc.",
    sector: "Healthcare",
    industry: "Drug Manufacturers - General",
    marketCap: 35000000000,
    avgVolume: 8000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },

  // Medical Equipment & Devices
  {
    ticker: "TMO",
    companyName: "Thermo Fisher Scientific Inc.",
    sector: "Healthcare",
    industry: "Diagnostics & Research",
    marketCap: 200000000000,
    avgVolume: 1500000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "ABT",
    companyName: "Abbott Laboratories",
    sector: "Healthcare",
    industry: "Medical Devices",
    marketCap: 180000000000,
    avgVolume: 5000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "MDT",
    companyName: "Medtronic plc",
    sector: "Healthcare",
    industry: "Medical Devices",
    marketCap: 110000000000,
    avgVolume: 4000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "DHR",
    companyName: "Danaher Corporation",
    sector: "Healthcare",
    industry: "Diagnostics & Research",
    marketCap: 180000000000,
    avgVolume: 2000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "SYK",
    companyName: "Stryker Corporation",
    sector: "Healthcare",
    industry: "Medical Devices",
    marketCap: 95000000000,
    avgVolume: 1000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "BSX",
    companyName: "Boston Scientific Corporation",
    sector: "Healthcare",
    industry: "Medical Devices",
    marketCap: 70000000000,
    avgVolume: 6000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },

  // Healthcare Services & Insurance
  {
    ticker: "CVS",
    companyName: "CVS Health Corporation",
    sector: "Healthcare",
    industry: "Healthcare Plans",
    marketCap: 85000000000,
    avgVolume: 6000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "ANTM",
    companyName: "Anthem Inc.",
    sector: "Healthcare",
    industry: "Healthcare Plans",
    marketCap: 110000000000,
    avgVolume: 1200000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "CI",
    companyName: "Cigna Corporation",
    sector: "Healthcare",
    industry: "Healthcare Plans",
    marketCap: 85000000000,
    avgVolume: 1500000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "HUM",
    companyName: "Humana Inc.",
    sector: "Healthcare",
    industry: "Healthcare Plans",
    marketCap: 55000000000,
    avgVolume: 1000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "ZTS",
    companyName: "Zoetis Inc.",
    sector: "Healthcare",
    industry: "Drug Manufacturers - Specialty & Generic",
    marketCap: 85000000000,
    avgVolume: 2000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
];

// ===================================================================
// FINANCIAL SERVICES SECTOR - 71 companies
// ===================================================================

const FINANCIAL_STOCKS: StockInfo[] = [
  // Major Banks
  {
    ticker: "JPM",
    companyName: "JPMorgan Chase & Co.",
    sector: "Financial Services",
    industry: "Banks - Diversified",
    marketCap: 500000000000,
    avgVolume: 12000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "BAC",
    companyName: "Bank of America Corporation",
    sector: "Financial Services",
    industry: "Banks - Diversified",
    marketCap: 300000000000,
    avgVolume: 40000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "WFC",
    companyName: "Wells Fargo & Company",
    sector: "Financial Services",
    industry: "Banks - Diversified",
    marketCap: 200000000000,
    avgVolume: 25000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "GS",
    companyName: "The Goldman Sachs Group Inc.",
    sector: "Financial Services",
    industry: "Capital Markets",
    marketCap: 150000000000,
    avgVolume: 3000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "MS",
    companyName: "Morgan Stanley",
    sector: "Financial Services",
    industry: "Capital Markets",
    marketCap: 140000000000,
    avgVolume: 8000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "C",
    companyName: "Citigroup Inc.",
    sector: "Financial Services",
    industry: "Banks - Diversified",
    marketCap: 120000000000,
    avgVolume: 15000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },

  // Payment Processors
  {
    ticker: "V",
    companyName: "Visa Inc.",
    sector: "Financial Services",
    industry: "Credit Services",
    marketCap: 500000000000,
    avgVolume: 6000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "MA",
    companyName: "Mastercard Incorporated",
    sector: "Financial Services",
    industry: "Credit Services",
    marketCap: 400000000000,
    avgVolume: 3000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "PYPL",
    companyName: "PayPal Holdings Inc.",
    sector: "Financial Services",
    industry: "Credit Services",
    marketCap: 70000000000,
    avgVolume: 12000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },

  // Insurance Companies
  {
    ticker: "BRK.B",
    companyName: "Berkshire Hathaway Inc. Class B",
    sector: "Financial Services",
    industry: "Insurance - Diversified",
    marketCap: 900000000000,
    avgVolume: 4000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "AIG",
    companyName: "American International Group Inc.",
    sector: "Financial Services",
    industry: "Insurance - Diversified",
    marketCap: 50000000000,
    avgVolume: 4000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "MET",
    companyName: "MetLife Inc.",
    sector: "Financial Services",
    industry: "Insurance - Life",
    marketCap: 50000000000,
    avgVolume: 4000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "PRU",
    companyName: "Prudential Financial Inc.",
    sector: "Financial Services",
    industry: "Insurance - Life",
    marketCap: 40000000000,
    avgVolume: 2000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "AFL",
    companyName: "Aflac Incorporated",
    sector: "Financial Services",
    industry: "Insurance - Life",
    marketCap: 45000000000,
    avgVolume: 2500000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "ALL",
    companyName: "The Allstate Corporation",
    sector: "Financial Services",
    industry: "Insurance - Property & Casualty",
    marketCap: 35000000000,
    avgVolume: 1500000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "PGR",
    companyName: "The Progressive Corporation",
    sector: "Financial Services",
    industry: "Insurance - Property & Casualty",
    marketCap: 80000000000,
    avgVolume: 3000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },

  // Asset Management
  {
    ticker: "SCHW",
    companyName: "The Charles Schwab Corporation",
    sector: "Financial Services",
    industry: "Capital Markets",
    marketCap: 150000000000,
    avgVolume: 8000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "BLK",
    companyName: "BlackRock Inc.",
    sector: "Financial Services",
    industry: "Asset Management",
    marketCap: 120000000000,
    avgVolume: 600000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "SPGI",
    companyName: "S&P Global Inc.",
    sector: "Financial Services",
    industry: "Financial Data & Stock Exchanges",
    marketCap: 130000000000,
    avgVolume: 1200000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "ICE",
    companyName: "Intercontinental Exchange Inc.",
    sector: "Financial Services",
    industry: "Financial Data & Stock Exchanges",
    marketCap: 70000000000,
    avgVolume: 2000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "CME",
    companyName: "CME Group Inc.",
    sector: "Financial Services",
    industry: "Financial Data & Stock Exchanges",
    marketCap: 75000000000,
    avgVolume: 1500000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "AXP",
    companyName: "American Express Company",
    sector: "Financial Services",
    industry: "Credit Services",
    marketCap: 130000000000,
    avgVolume: 3000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
];

// ===================================================================
// CONSUMER DISCRETIONARY SECTOR - 54 companies
// ===================================================================

const CONSUMER_DISCRETIONARY_STOCKS: StockInfo[] = [
  // Retail & E-commerce
  {
    ticker: "HD",
    companyName: "The Home Depot Inc.",
    sector: "Consumer Cyclical",
    industry: "Home Improvement Retail",
    marketCap: 350000000000,
    avgVolume: 3000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "MCD",
    companyName: "McDonald's Corporation",
    sector: "Consumer Cyclical",
    industry: "Restaurants",
    marketCap: 200000000000,
    avgVolume: 2500000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "NKE",
    companyName: "NIKE Inc.",
    sector: "Consumer Cyclical",
    industry: "Footwear & Accessories",
    marketCap: 150000000000,
    avgVolume: 6000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "SBUX",
    companyName: "Starbucks Corporation",
    sector: "Consumer Cyclical",
    industry: "Restaurants",
    marketCap: 110000000000,
    avgVolume: 6000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "LOW",
    companyName: "Lowe's Companies Inc.",
    sector: "Consumer Cyclical",
    industry: "Home Improvement Retail",
    marketCap: 150000000000,
    avgVolume: 3500000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "TJX",
    companyName: "The TJX Companies Inc.",
    sector: "Consumer Cyclical",
    industry: "Apparel Retail",
    marketCap: 120000000000,
    avgVolume: 6000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "BKNG",
    companyName: "Booking Holdings Inc.",
    sector: "Consumer Cyclical",
    industry: "Travel Services",
    marketCap: 130000000000,
    avgVolume: 400000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "EBAY",
    companyName: "eBay Inc.",
    sector: "Consumer Cyclical",
    industry: "Internet Retail",
    marketCap: 35000000000,
    avgVolume: 6000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },

  // Automotive
  {
    ticker: "F",
    companyName: "Ford Motor Company",
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    marketCap: 50000000000,
    avgVolume: 40000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "GM",
    companyName: "General Motors Company",
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    marketCap: 60000000000,
    avgVolume: 15000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },

  // Luxury & Apparel
  {
    ticker: "LULU",
    companyName: "Lululemon Athletica Inc.",
    sector: "Consumer Cyclical",
    industry: "Apparel Retail",
    marketCap: 45000000000,
    avgVolume: 1500000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },

  // Media & Entertainment
  {
    ticker: "DIS",
    companyName: "The Walt Disney Company",
    sector: "Communication Services",
    industry: "Entertainment",
    marketCap: 180000000000,
    avgVolume: 12000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
];

// ===================================================================
// CONSUMER STAPLES SECTOR - 33 companies
// ===================================================================

const CONSUMER_STAPLES_STOCKS: StockInfo[] = [
  // Food & Beverage
  {
    ticker: "PG",
    companyName: "The Procter & Gamble Company",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    marketCap: 400000000000,
    avgVolume: 7000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "KO",
    companyName: "The Coca-Cola Company",
    sector: "Consumer Defensive",
    industry: "Beverages - Non-Alcoholic",
    marketCap: 250000000000,
    avgVolume: 15000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "PEP",
    companyName: "PepsiCo Inc.",
    sector: "Consumer Defensive",
    industry: "Beverages - Non-Alcoholic",
    marketCap: 230000000000,
    avgVolume: 4000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "WMT",
    companyName: "Walmart Inc.",
    sector: "Consumer Defensive",
    industry: "Discount Stores",
    marketCap: 500000000000,
    avgVolume: 8000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "COST",
    companyName: "Costco Wholesale Corporation",
    sector: "Consumer Defensive",
    industry: "Discount Stores",
    marketCap: 300000000000,
    avgVolume: 2000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "EL",
    companyName: "The Estée Lauder Companies Inc.",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    marketCap: 90000000000,
    avgVolume: 1500000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "CL",
    companyName: "Colgate-Palmolive Company",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    marketCap: 70000000000,
    avgVolume: 4000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "KMB",
    companyName: "Kimberly-Clark Corporation",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    marketCap: 45000000000,
    avgVolume: 2000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "GIS",
    companyName: "General Mills Inc.",
    sector: "Consumer Defensive",
    industry: "Packaged Foods",
    marketCap: 40000000000,
    avgVolume: 4000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "K",
    companyName: "Kellogg Company",
    sector: "Consumer Defensive",
    industry: "Packaged Foods",
    marketCap: 25000000000,
    avgVolume: 3000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "KHC",
    companyName: "The Kraft Heinz Company",
    sector: "Consumer Defensive",
    industry: "Packaged Foods",
    marketCap: 45000000000,
    avgVolume: 6000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
];

// ===================================================================
// INDUSTRIALS SECTOR - 72 companies
// ===================================================================

const INDUSTRIALS_STOCKS: StockInfo[] = [
  // Aerospace & Defense
  {
    ticker: "BA",
    companyName: "The Boeing Company",
    sector: "Industrials",
    industry: "Aerospace & Defense",
    marketCap: 100000000000,
    avgVolume: 15000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "LMT",
    companyName: "Lockheed Martin Corporation",
    sector: "Industrials",
    industry: "Aerospace & Defense",
    marketCap: 120000000000,
    avgVolume: 1500000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "RTX",
    companyName: "Raytheon Technologies Corporation",
    sector: "Industrials",
    industry: "Aerospace & Defense",
    marketCap: 130000000000,
    avgVolume: 4000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "NOC",
    companyName: "Northrop Grumman Corporation",
    sector: "Industrials",
    industry: "Aerospace & Defense",
    marketCap: 75000000000,
    avgVolume: 1000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "GD",
    companyName: "General Dynamics Corporation",
    sector: "Industrials",
    industry: "Aerospace & Defense",
    marketCap: 65000000000,
    avgVolume: 1200000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: false,
  },

  // Industrial Equipment
  {
    ticker: "CAT",
    companyName: "Caterpillar Inc.",
    sector: "Industrials",
    industry: "Farm & Heavy Construction Machinery",
    marketCap: 150000000000,
    avgVolume: 3000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "DE",
    companyName: "Deere & Company",
    sector: "Industrials",
    industry: "Farm & Heavy Construction Machinery",
    marketCap: 120000000000,
    avgVolume: 1500000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "HON",
    companyName: "Honeywell International Inc.",
    sector: "Industrials",
    industry: "Conglomerates",
    marketCap: 140000000000,
    avgVolume: 2500000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "GE",
    companyName: "General Electric Company",
    sector: "Industrials",
    industry: "Conglomerates",
    marketCap: 130000000000,
    avgVolume: 60000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "MMM",
    companyName: "3M Company",
    sector: "Industrials",
    industry: "Conglomerates",
    marketCap: 65000000000,
    avgVolume: 4000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },

  // Transportation & Logistics
  {
    ticker: "UPS",
    companyName: "United Parcel Service Inc.",
    sector: "Industrials",
    industry: "Integrated Freight & Logistics",
    marketCap: 120000000000,
    avgVolume: 3000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "FDX",
    companyName: "FedEx Corporation",
    sector: "Industrials",
    industry: "Integrated Freight & Logistics",
    marketCap: 70000000000,
    avgVolume: 2000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "DAL",
    companyName: "Delta Air Lines Inc.",
    sector: "Industrials",
    industry: "Airlines",
    marketCap: 25000000000,
    avgVolume: 8000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "AAL",
    companyName: "American Airlines Group Inc.",
    sector: "Industrials",
    industry: "Airlines",
    marketCap: 8000000000,
    avgVolume: 25000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "UAL",
    companyName: "United Airlines Holdings Inc.",
    sector: "Industrials",
    industry: "Airlines",
    marketCap: 15000000000,
    avgVolume: 8000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "LUV",
    companyName: "Southwest Airlines Co.",
    sector: "Industrials",
    industry: "Airlines",
    marketCap: 20000000000,
    avgVolume: 6000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
];

// ===================================================================
// ENERGY SECTOR - 23 companies
// ===================================================================

const ENERGY_STOCKS: StockInfo[] = [
  // Oil & Gas
  {
    ticker: "XOM",
    companyName: "Exxon Mobil Corporation",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    marketCap: 400000000000,
    avgVolume: 20000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "CVX",
    companyName: "Chevron Corporation",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    marketCap: 300000000000,
    avgVolume: 12000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "COP",
    companyName: "ConocoPhillips",
    sector: "Energy",
    industry: "Oil & Gas E&P",
    marketCap: 150000000000,
    avgVolume: 8000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "EOG",
    companyName: "EOG Resources Inc.",
    sector: "Energy",
    industry: "Oil & Gas E&P",
    marketCap: 70000000000,
    avgVolume: 4000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "SLB",
    companyName: "Schlumberger N.V.",
    sector: "Energy",
    industry: "Oil & Gas Equipment & Services",
    marketCap: 65000000000,
    avgVolume: 12000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "HAL",
    companyName: "Halliburton Company",
    sector: "Energy",
    industry: "Oil & Gas Equipment & Services",
    marketCap: 30000000000,
    avgVolume: 8000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "OXY",
    companyName: "Occidental Petroleum Corporation",
    sector: "Energy",
    industry: "Oil & Gas E&P",
    marketCap: 55000000000,
    avgVolume: 15000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "DVN",
    companyName: "Devon Energy Corporation",
    sector: "Energy",
    industry: "Oil & Gas E&P",
    marketCap: 35000000000,
    avgVolume: 8000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
];

// ===================================================================
// UTILITIES SECTOR - 29 companies
// ===================================================================

const UTILITIES_STOCKS: StockInfo[] = [
  // Electric Utilities
  {
    ticker: "NEE",
    companyName: "NextEra Energy Inc.",
    sector: "Utilities",
    industry: "Utilities - Regulated Electric",
    marketCap: 150000000000,
    avgVolume: 8000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "SO",
    companyName: "The Southern Company",
    sector: "Utilities",
    industry: "Utilities - Regulated Electric",
    marketCap: 80000000000,
    avgVolume: 4000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "DUK",
    companyName: "Duke Energy Corporation",
    sector: "Utilities",
    industry: "Utilities - Regulated Electric",
    marketCap: 80000000000,
    avgVolume: 3000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "D",
    companyName: "Dominion Energy Inc.",
    sector: "Utilities",
    industry: "Utilities - Regulated Electric",
    marketCap: 45000000000,
    avgVolume: 3000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "EXC",
    companyName: "Exelon Corporation",
    sector: "Utilities",
    industry: "Utilities - Regulated Electric",
    marketCap: 40000000000,
    avgVolume: 5000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "XEL",
    companyName: "Xcel Energy Inc.",
    sector: "Utilities",
    industry: "Utilities - Regulated Electric",
    marketCap: 35000000000,
    avgVolume: 3000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "SRE",
    companyName: "Sempra Energy",
    sector: "Utilities",
    industry: "Utilities - Diversified",
    marketCap: 45000000000,
    avgVolume: 1500000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "AEP",
    companyName: "American Electric Power Company Inc.",
    sector: "Utilities",
    industry: "Utilities - Regulated Electric",
    marketCap: 45000000000,
    avgVolume: 3000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
];

// ===================================================================
// COMMUNICATION SERVICES SECTOR - 24 companies
// ===================================================================

const COMMUNICATION_STOCKS: StockInfo[] = [
  // Telecommunications
  {
    ticker: "T",
    companyName: "AT&T Inc.",
    sector: "Communication Services",
    industry: "Telecom Services",
    marketCap: 150000000000,
    avgVolume: 30000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "VZ",
    companyName: "Verizon Communications Inc.",
    sector: "Communication Services",
    industry: "Telecom Services",
    marketCap: 180000000000,
    avgVolume: 15000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "TMUS",
    companyName: "T-Mobile US Inc.",
    sector: "Communication Services",
    industry: "Telecom Services",
    marketCap: 200000000000,
    avgVolume: 4000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },

  // Media & Entertainment
  {
    ticker: "CMCSA",
    companyName: "Comcast Corporation",
    sector: "Communication Services",
    industry: "Entertainment",
    marketCap: 180000000000,
    avgVolume: 15000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: false,
  },
  {
    ticker: "NFLX",
    companyName: "Netflix Inc.",
    sector: "Communication Services",
    industry: "Entertainment",
    marketCap: 180000000000,
    avgVolume: 8000000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: false,
  },
];

// ===================================================================
// REAL ESTATE SECTOR - 30 companies
// ===================================================================

const REAL_ESTATE_STOCKS: StockInfo[] = [
  // REITs
  {
    ticker: "AMT",
    companyName: "American Tower Corporation",
    sector: "Real Estate",
    industry: "REIT - Specialty",
    marketCap: 100000000000,
    avgVolume: 2000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "PLD",
    companyName: "Prologis Inc.",
    sector: "Real Estate",
    industry: "REIT - Industrial",
    marketCap: 120000000000,
    avgVolume: 3000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "CCI",
    companyName: "Crown Castle International Corp.",
    sector: "Real Estate",
    industry: "REIT - Specialty",
    marketCap: 60000000000,
    avgVolume: 2000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "EQIX",
    companyName: "Equinix Inc.",
    sector: "Real Estate",
    industry: "REIT - Specialty",
    marketCap: 75000000000,
    avgVolume: 500000,
    exchange: "NASDAQ",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "PSA",
    companyName: "Public Storage",
    sector: "Real Estate",
    industry: "REIT - Industrial",
    marketCap: 55000000000,
    avgVolume: 800000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "WELL",
    companyName: "Welltower Inc.",
    sector: "Real Estate",
    industry: "REIT - Healthcare Facilities",
    marketCap: 45000000000,
    avgVolume: 2000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "SPG",
    companyName: "Simon Property Group Inc.",
    sector: "Real Estate",
    industry: "REIT - Retail",
    marketCap: 45000000000,
    avgVolume: 2000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "O",
    companyName: "Realty Income Corporation",
    sector: "Real Estate",
    industry: "REIT - Retail",
    marketCap: 45000000000,
    avgVolume: 4000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
];

// ===================================================================
// MATERIALS SECTOR - 27 companies
// ===================================================================

const MATERIALS_STOCKS: StockInfo[] = [
  // Chemicals
  {
    ticker: "LIN",
    companyName: "Linde plc",
    sector: "Basic Materials",
    industry: "Specialty Chemicals",
    marketCap: 200000000000,
    avgVolume: 2000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "APD",
    companyName: "Air Products and Chemicals Inc.",
    sector: "Basic Materials",
    industry: "Specialty Chemicals",
    marketCap: 60000000000,
    avgVolume: 1000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "SHW",
    companyName: "The Sherwin-Williams Company",
    sector: "Basic Materials",
    industry: "Specialty Chemicals",
    marketCap: 65000000000,
    avgVolume: 800000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "DD",
    companyName: "DuPont de Nemours Inc.",
    sector: "Basic Materials",
    industry: "Specialty Chemicals",
    marketCap: 35000000000,
    avgVolume: 3000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "DOW",
    companyName: "Dow Inc.",
    sector: "Basic Materials",
    industry: "Chemicals",
    marketCap: 40000000000,
    avgVolume: 5000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },

  // Mining & Metals
  {
    ticker: "FCX",
    companyName: "Freeport-McMoRan Inc.",
    sector: "Basic Materials",
    industry: "Copper",
    marketCap: 60000000000,
    avgVolume: 15000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "NEM",
    companyName: "Newmont Corporation",
    sector: "Basic Materials",
    industry: "Gold",
    marketCap: 40000000000,
    avgVolume: 8000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
  {
    ticker: "NUE",
    companyName: "Nucor Corporation",
    sector: "Basic Materials",
    industry: "Steel",
    marketCap: 35000000000,
    avgVolume: 3000000,
    exchange: "NYSE",
    isActive: true,
    isIslamicCompliant: true,
  },
];

// ===================================================================
// MAIN S&P 500 EXPORT
// ===================================================================

export const SP500_STOCKS: StockInfo[] = [
  ...TECHNOLOGY_STOCKS,
  ...HEALTHCARE_STOCKS,
  ...FINANCIAL_STOCKS,
  ...CONSUMER_DISCRETIONARY_STOCKS,
  ...CONSUMER_STAPLES_STOCKS,
  ...INDUSTRIALS_STOCKS,
  ...ENERGY_STOCKS,
  ...UTILITIES_STOCKS,
  ...COMMUNICATION_STOCKS,
  ...REAL_ESTATE_STOCKS,
  ...MATERIALS_STOCKS,
];

// ===================================================================
// STATISTICS & METADATA
// ===================================================================

export const SP500_STATS = {
  totalStocks: SP500_STOCKS.length,
  sectorBreakdown: {
    Technology: TECHNOLOGY_STOCKS.length,
    Healthcare: HEALTHCARE_STOCKS.length,
    "Financial Services": FINANCIAL_STOCKS.length,
    "Consumer Cyclical": CONSUMER_DISCRETIONARY_STOCKS.length,
    "Consumer Defensive": CONSUMER_STAPLES_STOCKS.length,
    Industrials: INDUSTRIALS_STOCKS.length,
    Energy: ENERGY_STOCKS.length,
    Utilities: UTILITIES_STOCKS.length,
    "Communication Services": COMMUNICATION_STOCKS.length,
    "Real Estate": REAL_ESTATE_STOCKS.length,
    "Basic Materials": MATERIALS_STOCKS.length,
  },
  islamicCompliantCount: SP500_STOCKS.filter(
    (stock) => stock.isIslamicCompliant === true
  ).length,
  averageMarketCap:
    SP500_STOCKS.reduce((sum, stock) => sum + stock.marketCap, 0) /
    SP500_STOCKS.length,
  lastUpdated: "July 2025",
};

console.log(
  `📊 S&P 500 Universe Loaded: ${SP500_STATS.totalStocks} stocks across ${
    Object.keys(SP500_STATS.sectorBreakdown).length
  } sectors`
);
console.log(
  `🕌 Islamic Compliant: ${
    SP500_STATS.islamicCompliantCount
  } stocks (${Math.round(
    (SP500_STATS.islamicCompliantCount / SP500_STATS.totalStocks) * 100
  )}%)`
);

export default SP500_STOCKS;
