
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ar' | 'de';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.signals': 'Signals',
    'nav.openPositions': 'Open Positions',
    'nav.ordersHistory': 'Orders History',
    'nav.historicalTrades': 'Historical Trades',
    'nav.admin': 'Admin',
    'nav.settings': 'Settings',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.howItWorks': 'How It Works',
    'nav.pricing': 'Pricing',
    'nav.signIn': 'Sign In',
    'nav.signUp': 'Sign Up',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    'nav.account': 'Account',
    'nav.adminPanel': 'Admin Panel',
    
    // Landing page
    'landing.getStarted': 'Get Started',
    'landing.signIn': 'Sign In',
    'landing.features': 'Features',
    'landing.pricing': 'Pricing',
    'landing.startTrial': 'Start Trial',
    'landing.trustedBy': 'Trusted By',
    'landing.testimonials': 'Testimonials',
    'landing.aiSignalsSmarter': 'AI Signals. Smarter Trades.',
    'landing.aiPoweredTrading': 'AI-Powered Trading',
    'landing.intelligencePlatform': 'Intelligence Platform',
    'landing.heroDescription': 'Join 2,847+ traders achieving +47% average annual returns with our real-time, multi-strategy signals that deliver 2:1 profit ratios on every trade.',
    'landing.winBigger': 'Win bigger than you lose (2:1 average)',
    'landing.highConviction': 'Only high-conviction setups (Score 80+)',
    'landing.riskOnly': 'Risk only 2% to make 4-6%',
    'landing.cancelAnytime': 'Cancel anytime',
    'landing.moneyBack': 'Money-back guarantee',
    'landing.startWith': 'Start with $0',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.activeSignals': 'Active Signals',
    'dashboard.todaysSignals': "Today's Signals",
    'dashboard.avgSignalScore': 'Avg Signal Score',
    'dashboard.successRate': 'Success Rate',
    'dashboard.bestPerformer': 'Best Performer',
    'dashboard.activeSignalsCount': 'Active Signals',
    'dashboard.latestSignal': 'Latest Signal',
    'dashboard.alerts': 'Alerts',
    'dashboard.recentTrades': 'Recent Trades',
    'dashboard.historicalTrades': 'Historical Trades',
    'dashboard.qualityThreshold': 'Quality threshold met',
    'dashboard.newSinceLastHour': 'new since last hour',
    'dashboard.signalsInPlay': 'signals in play',
    'dashboard.positionsNearTarget': 'positions near target',
    'dashboard.lastDays': 'Last 30 days',
    'dashboard.minAgo': 'min ago',
    'dashboard.winRate': 'Win Rate',
    'dashboard.portfolioPerformance': 'Portfolio Performance',
    'dashboard.targetPerformance': 'Target Performance',
    'dashboard.keepMonitoring': 'You\'ve reached the target performance level. Keep monitoring signals!',
    'dashboard.winningTrades': 'Winning Trades',
    'dashboard.totalTrades': 'Total Trades',
    'dashboard.losingTrades': 'Losing Trades',
    'dashboard.target': '≥60% Target',
    'dashboard.vsSnP500': 'vs S&P 500',
    'dashboard.portfolio': 'Portfolio',
    'dashboard.tradingIntelligence': 'trading intelligence dashboard',
    'dashboard.clickAnySignal': 'Click any signal below or go to the Signals tab to get started.',
    'dashboard.disclaimer': '*This is a simulation. No real capital is involved. Hypothetical results based on following all signals.',
    
    // Signals
    'signals.title': 'Trading Signals',
    'signals.subtitle': 'AI-powered trading signals with real-time analysis',
    'signals.timeframe': 'Timeframe',
    'signals.scoreThreshold': 'Score Threshold',
    'signals.market': 'Market',
    'signals.sector': 'Sector',
    'signals.shariahCompliant': 'Shariah Compliant Only',
    'signals.autoRefresh': 'Auto-refresh',
    'signals.lastUpdated': 'Last Updated',
    'signals.legend': 'Legend',
    'signals.strong': 'Strong',
    'signals.valid': 'Valid',
    'signals.weak': 'Weak',
    'signals.totalSignals': 'Total Signals',
    'signals.asset': 'Asset',
    'signals.currentPrice': 'Current Price',
    'signals.finalScore': 'Final Score',
    'signals.actions': 'Actions',
    'signals.view': 'View',
    'signals.noSignals': 'No signals match your current filters.',
    'signals.tryLowering': 'Try lowering the score threshold or changing the market/sector filter.',
    'signals.buySignalHeatmap': 'BUY Signal Heatmap',
    'signals.summaryReflects': 'Summary reflects weighted final scores (not just',
    'signals.only': 'only)',
    
    // Features
    'features.multiTimeframe': 'Multi Time Frame',
    'features.multiTimeframeDesc': 'Confirm trends, reduce false signals, and make more informed decisions.',
    'features.supportResistance': 'Multi-Level Support & Resistance',
    'features.supportResistanceDesc': 'Provide clearer entry/exit points and enhance trend confirmation.',
    'features.optionsFlow': 'Options Indicators',
    'features.optionsFlowDesc': 'Identifying trends, volatility, and potential entry/exit points.',
    
    // Settings
    'settings.title': 'Settings',
    'settings.notifications': 'Notifications',
    'settings.emailAlerts': 'Email Alerts',
    'settings.telegramAlerts': 'Telegram Alerts',
    'settings.pushNotifications': 'Push Notifications',
    'settings.digestFreq': 'Digest Frequency',
    'settings.language': 'Language & Locale',
    'settings.security': 'Security',
    'settings.changePassword': 'Change Password',
    'settings.twoFA': 'Two-Factor Authentication',
    'settings.lastLogin': 'Login Activity',
    'settings.api': 'API & Auto-Trading',
    'settings.autoTrading': 'Auto-Trading',
    'settings.brokerStatus': 'Broker Status',
    'settings.ui': 'UI & Data Preferences',
    'settings.showPnL': 'Show P&L Values',
    
    // Signal Modal
    'signalModal.signalDetails': 'Signal Details',
    'signalModal.technicalAnalysis': 'Technical Analysis',
    'signalModal.riskManagement': 'Risk Management',
    'signalModal.entryPrice': 'Entry Price',
    'signalModal.stopLoss': 'Stop Loss',
    'signalModal.takeProfit': 'Take Profit',
    'signalModal.riskReward': 'Risk/Reward',
    'signalModal.positionSize': 'Position Size',
    'signalModal.executeTrade': 'Execute Trade',
    'signalModal.cancel': 'Cancel',
    'signalModal.alreadyHavePosition': 'You already have a position in',
    'signalModal.considerRiskManagement': 'Consider your risk management strategy.',
    'signalModal.proceedAnyway': 'Proceed Anyway',
    'signalModal.tradeCancelled': 'Trade cancelled',
    'signalModal.tradeExecuted': 'Trade executed successfully!',
    
    // Admin
    'admin.title': 'Admin Center',
    'admin.subtitle': 'Manage your account settings and access support resources',
    'admin.helpFaq': 'Help/FAQ',
    'admin.privacyPolicy': 'Privacy Policy',
    'admin.accountSettings': 'Account Settings',
    'admin.documentation': 'Documentation',
    'admin.contactSupport': 'Contact Support',
    'admin.accountInfo': 'Account Information',
    'admin.accessHelpCenter': 'Access Help Center',
    'admin.viewPrivacyPolicy': 'View Privacy Policy',
    'admin.manageAccount': 'Manage Account',
    'admin.viewDocs': 'View Docs',
    'admin.emailSupport': 'Email Support',
    'admin.liveChat': 'Live Chat',
    
    // Footer
    'footer.platform': 'Platform',
    'footer.home': 'Home',
    'footer.features': 'Features',
    'footer.howItWorks': 'How It Works',
    'footer.support': 'Support',
    'footer.contact': 'Contact',
    'footer.discord': 'Discord',
    'footer.twitter': 'Twitter',
    'footer.legal': 'Legal',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.riskDisclosure': 'Risk Disclosure',
    'footer.shariahCompliance': 'Shariah Compliance',
    'footer.gdprCompliance': 'GDPR Compliance',
    'footer.cookieNotice': 'Cookie Notice',
    'footer.description': 'Advanced trading signals platform for Islamic finance compliance',
    'footer.shariahCompliantTag': 'Shariah Compliant',
    'footer.copyright': '© 2024 Kurzora. All rights reserved.',
    
    // Legal
    'legal.shariahCompliant': 'Shariah Compliant',
    'legal.tradingInvolves': 'Trading involves risk',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.subject': 'Subject',
    'common.message': 'Message',
    'common.sendMessage': 'Send Message',
    'common.on': 'ON',
    'common.off': 'OFF',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.score': 'Score',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.dashboard': 'لوحة التحكم',
    'nav.signals': 'الإشارات',
    'nav.openPositions': 'المراكز المفتوحة',
    'nav.ordersHistory': 'تاريخ الأوامر',
    'nav.historicalTrades': 'التداولات التاريخية',
    'nav.admin': 'الإدارة',
    'nav.settings': 'الإعدادات',
    'nav.about': 'حولنا',
    'nav.contact': 'اتصل بنا',
    'nav.howItWorks': 'كيف يعمل',
    'nav.pricing': 'الأسعار',
    'nav.signIn': 'تسجيل الدخول',
    'nav.signUp': 'إنشاء حساب',
    'nav.logout': 'تسجيل الخروج',
    'nav.profile': 'الملف الشخصي',
    'nav.account': 'الحساب',
    'nav.adminPanel': 'لوحة الإدارة',
    
    // Landing page
    'landing.getStarted': 'ابدأ الآن',
    'landing.signIn': 'تسجيل الدخول',
    'landing.features': 'الميزات',
    'landing.pricing': 'الأسعار',
    'landing.startTrial': 'ابدأ التجربة',
    'landing.trustedBy': 'موثوق من قبل',
    'landing.testimonials': 'الشهادات',
    'landing.aiSignalsSmarter': 'إشارات الذكاء الاصطناعي. تداولات أذكى.',
    'landing.aiPoweredTrading': 'التداول المدعوم بالذكاء الاصطناعي',
    'landing.intelligencePlatform': 'منصة الذكاء التجاري',
    'landing.heroDescription': 'انضم إلى أكثر من 2,847 متداولاً يحققون متوسط عوائد سنوية +47% مع إشاراتنا الفورية متعددة الاستراتيجيات التي تحقق نسب ربح 2:1 في كل صفقة.',
    'landing.winBigger': 'اربح أكثر مما تخسر (متوسط 2:1)',
    'landing.highConviction': 'فقط الإعدادات عالية القناعة (نقاط 80+)',
    'landing.riskOnly': 'خاطر بـ 2% فقط لتحقق 4-6%',
    'landing.cancelAnytime': 'إلغاء في أي وقت',
    'landing.moneyBack': 'ضمان استرداد الأموال',
    'landing.startWith': 'ابدأ بـ 0$',
    
    // Dashboard
    'dashboard.welcome': 'مرحباً',
    'dashboard.activeSignals': 'الإشارات النشطة',
    'dashboard.todaysSignals': 'إشارات اليوم',
    'dashboard.avgSignalScore': 'متوسط نقاط الإشارة',
    'dashboard.successRate': 'معدل النجاح',
    'dashboard.bestPerformer': 'الأفضل أداءً',
    'dashboard.activeSignalsCount': 'الإشارات النشطة',
    'dashboard.latestSignal': 'آخر إشارة',
    'dashboard.alerts': 'التنبيهات',
    'dashboard.recentTrades': 'التداولات الأخيرة',
    'dashboard.historicalTrades': 'التداولات التاريخية',
    'dashboard.qualityThreshold': 'تم الوصول لعتبة الجودة',
    'dashboard.newSinceLastHour': 'جديدة منذ آخر ساعة',
    'dashboard.signalsInPlay': 'إشارات قيد التشغيل',
    'dashboard.positionsNearTarget': 'مراكز قريبة من الهدف',
    'dashboard.lastDays': 'آخر 30 يوماً',
    'dashboard.minAgo': 'دقيقة مضت',
    'dashboard.winRate': 'معدل الفوز',
    'dashboard.portfolioPerformance': 'أداء المحفظة',
    'dashboard.targetPerformance': 'الأداء المستهدف',
    'dashboard.keepMonitoring': 'لقد وصلت إلى مستوى الأداء المستهدف. استمر في مراقبة الإشارات!',
    'dashboard.winningTrades': 'الصفقات الرابحة',
    'dashboard.totalTrades': 'إجمالي الصفقات',
    'dashboard.losingTrades': 'الصفقات الخاسرة',
    'dashboard.target': '≥60% الهدف',
    'dashboard.vsSnP500': 'مقابل S&P 500',
    'dashboard.portfolio': 'المحفظة',
    'dashboard.tradingIntelligence': 'لوحة معلومات الذكاء التجاري',
    'dashboard.clickAnySignal': 'انقر على أي إشارة أدناه أو اذهب إلى علامة تبويب الإشارات للبدء.',
    'dashboard.disclaimer': '*هذه محاكاة. لا رأس مال حقيقي متضمن. النتائج الافتراضية مبنية على اتباع جميع الإشارات.',
    
    // Signals
    'signals.title': 'إشارات التداول',
    'signals.subtitle': 'إشارات التداول المدعومة بالذكاء الاصطناعي مع التحليل الفوري',
    'signals.timeframe': 'الإطار الزمني',
    'signals.scoreThreshold': 'عتبة النقاط',
    'signals.market': 'السوق',
    'signals.sector': 'القطاع',
    'signals.shariahCompliant': 'متوافق مع الشريعة فقط',
    'signals.autoRefresh': 'التحديث التلقائي',
    'signals.lastUpdated': 'آخر تحديث',
    'signals.legend': 'المفتاح',
    'signals.strong': 'قوي',
    'signals.valid': 'صحيح',
    'signals.weak': 'ضعيف',
    'signals.totalSignals': 'إجمالي الإشارات',
    'signals.asset': 'الأصل',
    'signals.currentPrice': 'السعر الحالي',
    'signals.finalScore': 'النقاط النهائية',
    'signals.actions': 'الإجراءات',
    'signals.view': 'عرض',
    'signals.noSignals': 'لا توجد إشارات تطابق المرشحات الحالية.',
    'signals.tryLowering': 'حاول خفض عتبة النقاط أو تغيير مرشح السوق/القطاع.',
    'signals.buySignalHeatmap': 'خريطة إشارات الشراء الحرارية',
    'signals.summaryReflects': 'الملخص يعكس النقاط النهائية المرجحة (وليس',
    'signals.only': 'فقط)',
    
    // Features
    'features.multiTimeframe': 'إطارات زمنية متعددة',
    'features.multiTimeframeDesc': 'تأكيد الاتجاهات وتقليل الإشارات الخاطئة واتخاذ قرارات أكثر دقة.',
    'features.supportResistance': 'دعم ومقاومة متعدد المستويات',
    'features.supportResistanceDesc': 'توفير نقاط دخول وخروج أوضح وتعزيز تأكيد الاتجاه.',
    'features.optionsFlow': 'مؤشرات الخيارات',
    'features.optionsFlowDesc': 'تحديد الاتجاهات والتقلبات ونقاط الدخول والخروج المحتملة.',
    
    // Settings
    'settings.title': 'الإعدادات',
    'settings.notifications': 'الإشعارات',
    'settings.emailAlerts': 'تنبيهات البريد الإلكتروني',
    'settings.telegramAlerts': 'تنبيهات تليجرام',
    'settings.pushNotifications': 'الإشعارات الفورية',
    'settings.digestFreq': 'تكرار الملخص',
    'settings.language': 'اللغة والإعدادات المحلية',
    'settings.security': 'الأمان',
    'settings.changePassword': 'تغيير كلمة المرور',
    'settings.twoFA': 'المصادقة الثنائية',
    'settings.lastLogin': 'نشاط تسجيل الدخول',
    'settings.api': 'API والتداول التلقائي',
    'settings.autoTrading': 'التداول التلقائي',
    'settings.brokerStatus': 'حالة الوسيط',
    'settings.ui': 'واجهة المستخدم وتفضيلات البيانات',
    'settings.showPnL': 'إظهار قيم الربح والخسارة',
    
    // Signal Modal
    'signalModal.signalDetails': 'تفاصيل الإشارة',
    'signalModal.technicalAnalysis': 'التحليل الفني',
    'signalModal.riskManagement': 'إدارة المخاطر',
    'signalModal.entryPrice': 'سعر الدخول',
    'signalModal.stopLoss': 'وقف الخسارة',
    'signalModal.takeProfit': 'جني الأرباح',
    'signalModal.riskReward': 'نسبة المخاطرة/المكافأة',
    'signalModal.positionSize': 'حجم المركز',
    'signalModal.executeTrade': 'تنفيذ التداول',
    'signalModal.cancel': 'إلغاء',
    'signalModal.alreadyHavePosition': 'لديك بالفعل مركز في',
    'signalModal.considerRiskManagement': 'فكر في استراتيجية إدارة المخاطر.',
    'signalModal.proceedAnyway': 'المتابعة على أي حال',
    'signalModal.tradeCancelled': 'تم إلغاء التداول',
    'signalModal.tradeExecuted': 'تم تنفيذ التداول بنجاح!',
    
    // Admin
    'admin.title': 'مركز الإدارة',
    'admin.subtitle': 'إدارة إعدادات الحساب والوصول لموارد الدعم',
    'admin.helpFaq': 'المساعدة/الأسئلة الشائعة',
    'admin.privacyPolicy': 'سياسة الخصوصية',
    'admin.accountSettings': 'إعدادات الحساب',
    'admin.documentation': 'التوثيق',
    'admin.contactSupport': 'اتصل بالدعم',
    'admin.accountInfo': 'معلومات الحساب',
    'admin.accessHelpCenter': 'الوصول لمركز المساعدة',
    'admin.viewPrivacyPolicy': 'عرض سياسة الخصوصية',
    'admin.manageAccount': 'إدارة الحساب',
    'admin.viewDocs': 'عرض التوثيق',
    'admin.emailSupport': 'دعم البريد الإلكتروني',
    'admin.liveChat': 'الدردشة المباشرة',
    
    // Footer
    'footer.platform': 'المنصة',
    'footer.home': 'الرئيسية',
    'footer.features': 'الميزات',
    'footer.howItWorks': 'كيف يعمل',
    'footer.support': 'الدعم',
    'footer.contact': 'اتصل بنا',
    'footer.discord': 'ديسكورد',
    'footer.twitter': 'تويتر',
    'footer.legal': 'قانوني',
    'footer.privacyPolicy': 'سياسة الخصوصية',
    'footer.termsOfService': 'شروط الخدمة',
    'footer.riskDisclosure': 'إفصاح المخاطر',
    'footer.shariahCompliance': 'الامتثال الشرعي',
    'footer.gdprCompliance': 'امتثال GDPR',
    'footer.cookieNotice': 'إشعار ملفات تعريف الارتباط',
    'footer.description': 'منصة إشارات التداول المتقدمة للامتثال للتمويل الإسلامي',
    'footer.shariahCompliantTag': 'متوافق مع الشريعة',
    'footer.copyright': '© 2024 كورزورا. جميع الحقوق محفوظة.',
    
    // Legal
    'legal.shariahCompliant': 'متوافق مع الشريعة',
    'legal.tradingInvolves': 'التداول ينطوي على مخاطر',
    
    // Common
    'common.loading': 'جارٍ التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تحرير',
    'common.create': 'إنشاء',
    'common.update': 'تحديث',
    'common.close': 'إغلاق',
    'common.submit': 'إرسال',
    'common.search': 'بحث',
    'common.filter': 'مرشح',
    'common.all': 'الكل',
    'common.name': 'الاسم',
    'common.email': 'البريد الإلكتروني',
    'common.phone': 'الهاتف',
    'common.address': 'العنوان',
    'common.subject': 'الموضوع',
    'common.message': 'الرسالة',
    'common.sendMessage': 'إرسال الرسالة',
    'common.on': 'مفعل',
    'common.off': 'مطفأ',
    'common.enabled': 'مفعل',
    'common.disabled': 'معطل',
    'common.score': 'النقاط',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.dashboard': 'Dashboard',
    'nav.signals': 'Signale',
    'nav.openPositions': 'Offene Positionen',
    'nav.ordersHistory': 'Orderhistorie',
    'nav.historicalTrades': 'Historische Trades',
    'nav.admin': 'Admin',
    'nav.settings': 'Einstellungen',
    'nav.about': 'Über uns',
    'nav.contact': 'Kontakt',
    'nav.howItWorks': 'Wie es funktioniert',
    'nav.pricing': 'Preise',
    'nav.signIn': 'Anmelden',
    'nav.signUp': 'Registrieren',
    'nav.logout': 'Abmelden',
    'nav.profile': 'Profil',
    'nav.account': 'Konto',
    'nav.adminPanel': 'Admin-Panel',
    
    // Landing page
    'landing.getStarted': 'Loslegen',
    'landing.signIn': 'Anmelden',
    'landing.features': 'Funktionen',
    'landing.pricing': 'Preise',
    'landing.startTrial': 'Testversion starten',
    'landing.trustedBy': 'Vertraut von',
    'landing.testimonials': 'Bewertungen',
    'landing.aiSignalsSmarter': 'KI-Signale. Intelligentere Trades.',
    'landing.aiPoweredTrading': 'KI-gestütztes Trading',
    'landing.intelligencePlatform': 'Intelligence-Plattform',
    'landing.heroDescription': 'Schließen Sie sich 2.847+ Tradern an, die durchschnittlich +47% jährliche Renditen mit unseren Echtzeit-Multi-Strategie-Signalen erzielen, die 2:1 Gewinnverhältnisse bei jedem Trade liefern.',
    'landing.winBigger': 'Gewinnen Sie mehr als Sie verlieren (2:1 Durchschnitt)',
    'landing.highConviction': 'Nur hochüberzeugte Setups (Score 80+)',
    'landing.riskOnly': 'Riskieren Sie nur 2% um 4-6% zu verdienen',
    'landing.cancelAnytime': 'Jederzeit kündbar',
    'landing.moneyBack': 'Geld-zurück-Garantie',
    'landing.startWith': 'Beginnen Sie mit 0$',
    
    // Dashboard
    'dashboard.welcome': 'Willkommen',
    'dashboard.activeSignals': 'Aktive Signale',
    'dashboard.todaysSignals': 'Heutige Signale',
    'dashboard.avgSignalScore': 'Durchschn. Signal-Score',
    'dashboard.successRate': 'Erfolgsrate',
    'dashboard.bestPerformer': 'Bester Performer',
    'dashboard.activeSignalsCount': 'Aktive Signale',
    'dashboard.latestSignal': 'Neuestes Signal',
    'dashboard.alerts': 'Benachrichtigungen',
    'dashboard.recentTrades': 'Letzte Trades',
    'dashboard.historicalTrades': 'Historische Trades',
    'dashboard.qualityThreshold': 'Qualitätsschwelle erreicht',
    'dashboard.newSinceLastHour': 'neu seit letzter Stunde',
    'dashboard.signalsInPlay': 'Signale im Spiel',
    'dashboard.positionsNearTarget': 'Positionen nahe Ziel',
    'dashboard.lastDays': 'Letzte 30 Tage',
    'dashboard.minAgo': 'Min. her',
    'dashboard.winRate': 'Gewinnrate',
    'dashboard.portfolioPerformance': 'Portfolio-Performance',
    'dashboard.targetPerformance': 'Ziel-Performance',
    'dashboard.keepMonitoring': 'Sie haben das Ziel-Performance-Level erreicht. Behalten Sie die Signale im Auge!',
    'dashboard.winningTrades': 'Gewinnende Trades',
    'dashboard.totalTrades': 'Gesamte Trades',
    'dashboard.losingTrades': 'Verlierende Trades',
    'dashboard.target': '≥60% Ziel',
    'dashboard.vsSnP500': 'vs S&P 500',
    'dashboard.portfolio': 'Portfolio',
    'dashboard.tradingIntelligence': 'Trading-Intelligence-Dashboard',
    'dashboard.clickAnySignal': 'Klicken Sie auf ein beliebiges Signal unten oder gehen Sie zur Signale-Registerkarte, um zu beginnen.',
    'dashboard.disclaimer': '*Dies ist eine Simulation. Kein echtes Kapital ist beteiligt. Hypothetische Ergebnisse basierend auf der Befolgung aller Signale.',
    
    // Signals
    'signals.title': 'Trading-Signale',
    'signals.subtitle': 'KI-gestützte Trading-Signale mit Echtzeitanalyse',
    'signals.timeframe': 'Zeitrahmen',
    'signals.scoreThreshold': 'Score-Schwelle',
    'signals.market': 'Markt',
    'signals.sector': 'Sektor',
    'signals.shariahCompliant': 'Nur Scharia-konform',
    'signals.autoRefresh': 'Auto-Aktualisierung',
    'signals.lastUpdated': 'Zuletzt aktualisiert',
    'signals.legend': 'Legende',
    'signals.strong': 'Stark',
    'signals.valid': 'Gültig',
    'signals.weak': 'Schwach',
    'signals.totalSignals': 'Gesamtsignale',
    'signals.asset': 'Anlage',
    'signals.currentPrice': 'Aktueller Preis',
    'signals.finalScore': 'Endpunktzahl',
    'signals.actions': 'Aktionen',
    'signals.view': 'Anzeigen',
    'signals.noSignals': 'Keine Signale entsprechen Ihren aktuellen Filtern.',
    'signals.tryLowering': 'Versuchen Sie, die Score-Schwelle zu senken oder den Markt-/Sektorfilter zu ändern.',
    'signals.buySignalHeatmap': 'KAUF Signal-Heatmap',
    'signals.summaryReflects': 'Zusammenfassung spiegelt gewichtete Endpunktzahl wider (nicht nur',
    'signals.only': ')',
    
    // Features
    'features.multiTimeframe': 'Mehrere Zeitrahmen',
    'features.multiTimeframeDesc': 'Trends bestätigen, falsche Signale reduzieren und informiertere Entscheidungen treffen.',
    'features.supportResistance': 'Mehrstufige Unterstützung & Widerstand',
    'features.supportResistanceDesc': 'Klarere Ein-/Ausstiegspunkte bieten und Trendbestätigung verbessern.',
    'features.optionsFlow': 'Options-Indikatoren',
    'features.optionsFlowDesc': 'Trends, Volatilität und potenzielle Ein-/Ausstiegspunkte identifizieren.',
    
    // Settings
    'settings.title': 'Einstellungen',
    'settings.notifications': 'Benachrichtigungen',
    'settings.emailAlerts': 'E-Mail-Benachrichtigungen',
    'settings.telegramAlerts': 'Telegram-Benachrichtigungen',
    'settings.pushNotifications': 'Push-Benachrichtigungen',
    'settings.digestFreq': 'Digest-Häufigkeit',
    'settings.language': 'Sprache & Lokalisierung',
    'settings.security': 'Sicherheit',
    'settings.changePassword': 'Passwort ändern',
    'settings.twoFA': 'Zwei-Faktor-Authentifizierung',
    'settings.lastLogin': 'Login-Aktivität',
    'settings.api': 'API & Auto-Trading',
    'settings.autoTrading': 'Auto-Trading',
    'settings.brokerStatus': 'Broker-Status',
    'settings.ui': 'UI & Datenpräferenzen',
    'settings.showPnL': 'P&L-Werte anzeigen',
    
    // Signal Modal
    'signalModal.signalDetails': 'Signal-Details',
    'signalModal.technicalAnalysis': 'Technische Analyse',
    'signalModal.riskManagement': 'Risikomanagement',
    'signalModal.entryPrice': 'Einstiegspreis',
    'signalModal.stopLoss': 'Stop Loss',
    'signalModal.takeProfit': 'Take Profit',
    'signalModal.riskReward': 'Risiko/Ertrag',
    'signalModal.positionSize': 'Positionsgröße',
    'signalModal.executeTrade': 'Trade ausführen',
    'signalModal.cancel': 'Abbrechen',
    'signalModal.alreadyHavePosition': 'Sie haben bereits eine Position in',
    'signalModal.considerRiskManagement': 'Bedenken Sie Ihre Risikomanagement-Strategie.',
    'signalModal.proceedAnyway': 'Trotzdem fortfahren',
    'signalModal.tradeCancelled': 'Trade abgebrochen',
    'signalModal.tradeExecuted': 'Trade erfolgreich ausgeführt!',
    
    // Admin
    'admin.title': 'Admin-Center',
    'admin.subtitle': 'Verwalten Sie Ihre Kontoeinstellungen und greifen Sie auf Support-Ressourcen zu',
    'admin.helpFaq': 'Hilfe/FAQ',
    'admin.privacyPolicy': 'Datenschutzrichtlinie',
    'admin.accountSettings': 'Kontoeinstellungen',
    'admin.documentation': 'Dokumentation',
    'admin.contactSupport': 'Support kontaktieren',
    'admin.accountInfo': 'Kontoinformationen',
    'admin.accessHelpCenter': 'Hilfe-Center aufrufen',
    'admin.viewPrivacyPolicy': 'Datenschutzrichtlinie anzeigen',
    'admin.manageAccount': 'Konto verwalten',
    'admin.viewDocs': 'Dokumentation anzeigen',
    'admin.emailSupport': 'E-Mail-Support',
    'admin.liveChat': 'Live-Chat',
    
    // Footer
    'footer.platform': 'Plattform',
    'footer.home': 'Startseite',
    'footer.features': 'Funktionen',
    'footer.howItWorks': 'Wie es funktioniert',
    'footer.support': 'Support',
    'footer.contact': 'Kontakt',
    'footer.discord': 'Discord',
    'footer.twitter': 'Twitter',
    'footer.legal': 'Rechtliches',
    'footer.privacyPolicy': 'Datenschutzrichtlinie',
    'footer.termsOfService': 'Nutzungsbedingungen',
    'footer.riskDisclosure': 'Risikohinweis',
    'footer.shariahCompliance': 'Scharia-Konformität',
    'footer.gdprCompliance': 'DSGVO-Konformität',
    'footer.cookieNotice': 'Cookie-Hinweis',
    'footer.description': 'Erweiterte Handelssignale-Plattform für islamische Finanzkonformität',
    'footer.shariahCompliantTag': 'Scharia-konform',
    'footer.copyright': '© 2024 Kurzora. Alle Rechte vorbehalten.',
    
    // Legal
    'legal.shariahCompliant': 'Scharia-konform',
    'legal.tradingInvolves': 'Trading birgt Risiken',
    
    // Common
    'common.loading': 'Wird geladen...',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.create': 'Erstellen',
    'common.update': 'Aktualisieren',
    'common.close': 'Schließen',
    'common.submit': 'Senden',
    'common.search': 'Suchen',
    'common.filter': 'Filter',
    'common.all': 'Alle',
    'common.name': 'Name',
    'common.email': 'E-Mail',
    'common.phone': 'Telefon',
    'common.address': 'Adresse',
    'common.subject': 'Betreff',
    'common.message': 'Nachricht',
    'common.sendMessage': 'Nachricht senden',
    'common.on': 'EIN',
    'common.off': 'AUS',
    'common.enabled': 'Aktiviert',
    'common.disabled': 'Deaktiviert',
    'common.score': 'Punktzahl',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageProvider;
